version: '3.8'

services:
  coturn:
    platform: linux/arm64
    image: coturn/coturn:latest
    container_name: coturn
    volumes:
      - ./config/turnserver.dev.conf:/etc/coturn/turnserver.conf:ro
    command: ["-c", "/etc/coturn/turnserver.conf"]
    restart: unless-stopped
    network_mode: host
    ports:
      - "3478:3478"
      - "3478:3478/udp"
      - "49152-65535:49152-65535/udp"

  webrtc-server:
    platform: linux/arm64
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/arm64
    container_name: go-webrtc-server-arm64
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: host
    shm_size: 1g
    security_opt:
      - seccomp:unconfined
    ulimits:
      memlock:
        soft: -1
        hard: -1
      stack:
        soft: 67108864
        hard: 67108864
      rtprio: 99
    environment:
      - TURN_PASSWORD=password
      - JACK_NO_AUDIO_RESERVATION=1
      - JACK_OPTIONS=-R -d dummy
      - JACK_SAMPLE_RATE=48000
      - GST_DEBUG=2
      - XDG_RUNTIME_DIR=/tmp/runtime-appuser
    depends_on:
      - coturn
    cap_add:
      - SYS_NICE
    ports:
      - "8080:8080"  # HTTP server
      - "49152-65535:49152-65535/udp"  # WebRTC media ports
      - "10000-10100:10000-10100"