version: '3.8'

services:
  webrtc-server:
    platform: linux/arm64
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/arm64
    container_name: server-arm64
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./client:/app/client
      - ./supercollider/src:/app/supercollider/src
      - ./supercollider/synthdefs:/app/supercollider/synthdefs
    shm_size: 1g
    security_opt:
      - seccomp:unconfined
    ulimits:
      memlock:
        soft: -1
        hard: -1
      stack:
        soft: 67108864
        hard: 67108864
      rtprio: 99
    environment:
      - JACK_NO_AUDIO_RESERVATION=1
      - JACK_PORT_MAX=128
      - GST_DEBUG=2
      - XDG_RUNTIME_DIR=/tmp/runtime-appuser
      - AWESTRUCK_ENV=development
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - AWESTRUCK_API_KEY=${AWESTRUCK_API_KEY}
      - STUN_SERVER=localhost:3478
    cap_add:
      - SYS_NICE
    network_mode: host
    depends_on:
      stun-server:
        condition: service_healthy

  stun-server:
    platform: linux/arm64
    build:
      context: .
      dockerfile: Dockerfile.stun
      platforms:
        - linux/arm64
    container_name: stun-server-arm64
    ports:
      - "3478:3478/udp"
      - "3479:3479/tcp"
    network_mode: host
    restart: unless-stopped
    # why we use more aggressive healthcheck timing in development:
    # - faster feedback loop for local development
    # - less resource constrained than production
    # - quicker container replacement on failure
    healthcheck:
      test: ["CMD-SHELL", "nc -zv localhost 3479 2>/dev/null || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 2s