version: '3.8'

networks:
  awestruck_network:
    driver: bridge

services:
  webrtc:
    build:
      context: .
      dockerfile: Dockerfile
    image: go-webrtc-server-linux-arm64
    container_name: go-webrtc-server-linux-arm64-instance
    platform: linux/arm64
    ports:
      - "8080:8080"
      - "10000-10010:10000-10010/udp"
    networks:
      - awestruck_network
    environment:
      - JACK_NO_AUDIO_RESERVATION=1
      - JACK_OPTIONS=-R -d dummy
      - JACK_SAMPLE_RATE=48000
    ulimits:
      memlock:
        soft: -1
        hard: -1
      stack:
        soft: 67108864
        hard: 67108864
    shm_size: 1g
    depends_on:
      - coturn

  coturn:
    image: coturn/coturn
    container_name: coturn
    networks:
      - awestruck_network
    ports:
      - "3478:3478"
      - "3478:3478/udp"
      - "5349:5349"
      - "5349:5349/udp"
      - "10000-10010:10000-10010/udp"
    volumes:
      - ./coturn.conf:/etc/coturn/turnserver.conf
    restart: unless-stopped