version: '3.8'

services:
  webrtc-server:
    platform: linux/arm64
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/arm64
    container_name: server-arm64
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./client:/app/client
      - ./supercollider/src:/app/supercollider/src
      - ./supercollider/synthdefs:/app/supercollider/synthdefs
    shm_size: 1g
    security_opt:
      - seccomp:unconfined
    ulimits:
      memlock:
        soft: -1
        hard: -1
      stack:
        soft: 67108864
        hard: 67108864
      rtprio: 99
    environment:
      - JACK_NO_AUDIO_RESERVATION=1
      - JACK_OPTIONS=-R -d dummy
      - JACK_SAMPLE_RATE=48000
      - GST_DEBUG=2
      - XDG_RUNTIME_DIR=/tmp/runtime-appuser
      - AWESTRUCK_ENV=development
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - AWESTRUCK_API_KEY=${AWESTRUCK_API_KEY}
      - STUN_SERVER=localhost:3478
    cap_add:
      - SYS_NICE
    network_mode: host
    depends_on:
      - stun-server

  stun-server:
    platform: linux/arm64
    build:
      context: .
      dockerfile: Dockerfile.stun
      platforms:
        - linux/arm64
    container_name: stun-server-arm64
    environment:
      - STUN_PORT=3478
    network_mode: host
    restart: unless-stopped