version: '3.8'

# why we need multiple networks:
# - simulates aws vpc networking
# - enables service isolation
# - replicates load balancer setup
networks:
  frontend:
    name: frontend
  backend:
    name: backend

services:
  webrtc-server:
    build:
      context: .
      dockerfile: Dockerfile
    # why we need bridge networking:
    # - matches production port mappings
    # - validates container networking
    # - ensures proper service discovery
    networks:
      - backend
    volumes:
      - ./client:/app/client
      - ./supercollider:/app/supercollider
      - ./server:/app/server
    environment:
      - AWESTRUCK_ENV=development
      - TURN_SERVER_HOST=${HOST_IP:-$(./scripts/get_host_ip.sh)}
      - TURN_USERNAME=awestruck_user
      - TURN_PASSWORD=verySecurePassword1234567890abcdefghijklmnop
      # MAYBE REMOVE?
      - XDG_RUNTIME_DIR=/tmp/runtime-appuser
      # AUDIO SETTINGS
      - GST_DEBUG=2
      - GST_BUFFER_SIZE=4194304
      - JACK_NO_AUDIO_RESERVATION=1
      - JACK_PORT_MAX=128
      - JACK_PERIOD_SIZE=1024
      - JACK_PERIODS=2
      - JACK_PRIORITY=95
      - JACK_REALTIME_PRIORITY=95
      - JACK_TIMEOUT=2000
      - JACK_BUFFER_SIZE=2048
      # SECRETS
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - AWESTRUCK_API_KEY=${AWESTRUCK_API_KEY}
    ports:
      - "8080:8080"
    depends_on:
      - turn-server

  # why we need turn-server:
  # - provides consistent turn setup locally
  # - enables testing of ice candidates
  # - mirrors aws turn configuration
  turn-server:
    build:
      context: .
      dockerfile: Dockerfile.turn2
    # why we need bridge networking:
    # - validates port mappings for production
    # - ensures proper udp relay ports
    # - matches aws networking model
    networks:
      - backend
    ports:
      - "3478:3478/udp"  # TURN UDP
      - "3479:3479/tcp"  # TURN control
      - "49152-49252:49152-49252/udp"  # TURN relay ports
    environment:
      - AWESTRUCK_ENV=development
      - TURN_REALM=localhost
      - PUBLIC_IP=${HOST_IP:-$(./scripts/get_host_ip.sh)}
      - USERS=awestruck_user=verySecurePassword1234567890abcdefghijklmnop
      - TURN_USERNAME=awestruck_user
      - TURN_PASSWORD=verySecurePassword1234567890abcdefghijklmnop
      - MIN_PORT=49152
      - MAX_PORT=49252