version: '3.8'

services:
  # why we need a webrtc service:
  # - handles audio synthesis and streaming
  # - manages webrtc connections
  # - provides api endpoints
  webrtc-server:
    platform: linux/arm64
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/arm64
    container_name: server-arm64
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./client:/app/client
      - ./supercollider/src:/app/supercollider/src
      - ./supercollider/synthdefs:/app/supercollider/synthdefs
    shm_size: 1g
    security_opt:
      - seccomp:unconfined
    ulimits:
      memlock:
        soft: -1
        hard: -1
      stack:
        soft: 67108864
        hard: 67108864
      rtprio: 99
    environment:
      - DEPLOYMENT_TIMESTAMP=${DEPLOYMENT_TIMESTAMP:-}
      - AWESTRUCK_ENV=development
      - JACK_NO_AUDIO_RESERVATION=1
      - JACK_PORT_MAX=128
      - GST_DEBUG=2
      - XDG_RUNTIME_DIR=/tmp/runtime-appuser
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - AWESTRUCK_API_KEY=${AWESTRUCK_API_KEY}
      - STUN_SERVER=localhost:3478
      - GST_BUFFER_SIZE=4194304
    cap_add:
      - SYS_NICE
    network_mode: host
    depends_on:
      turn-server:
        condition: service_healthy
  # why we need a turn service:
  # - provides both stun and turn functionality
  # - enables nat traversal for webrtc
  # - improves connection reliability
  turn-server:
    build:
      context: .
      dockerfile: Dockerfile.turn
    platform: linux/arm64
    container_name: turn-server-linux-arm64-instance
    ports:
      - "3478:3478/udp"
      - "3479:3479"
    environment:
      - DEPLOYMENT_TIMESTAMP=${DEPLOYMENT_TIMESTAMP:-}
    volumes:
      - ./turn:/app/turn
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3479/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 5s